
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";
import { Merriweather } from "next/font/google";
import { Toaster } from "react-hot-toast";


 
export const merriWeather = Merriweather({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
    >
      <body className={`bg-white ${merriWeather.className}`}>
        <Navbar/>
        <main className="bg-white">
        {children}
        </main>

        <Toaster />

        <Footer/>
        </body>
    </html>
  );
}
